name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: tshirts fail
      run: |
        g++ -Wall -Wextra -Werror tshirts.cpp -o tshirts.out
    - name: run
      run: ./tshirts

    - name: misaligned fail
      run: |
        g++ -Wall -Wextra -Werror misaligned.cpp -o misaligned.out
    - name: run
      run: ./misaligned

    - name: alerter fail
      run: |
        g++ -Wall -Wextra -Werror alerter.cpp -o alerter.out
    - name: run
      run: ./alerter
